# WRITE TEMPORARY CNF-FILES FOR MODES


def write_cnf_gauss(n, temp):

    with open(temp+'/gauss.cnf_ERA5', 'w') as f:
        f.writelines(['&gaussian\n',
            '   N           = '+str(n)+'\n',
            "   gauss_fname = '"+temp+"gauss/gauss_ERA5.data'\n",
            '/\n'])


def write_cnf_vsf(levels, sigma_file, gamma_file, num_vmode, temp):

    with open(temp+'/vsfcalc.cnf_ERA5', 'w') as f:
        f.writelines(['&vsfcalc_cnf\n',
 "   stab_fname       = '"+gamma_file+"'\n",
 "   vgrid_fname      = '"+sigma_file+"'\n",
 "   vsf_fname        = '"+temp+"vsf/vsf_ERA5.data'\n",
 "   equiheight_fname = '"+temp+"vsf/equi_ERA5.data'\n",
 '   num_vmode        = '+str(num_vmode)+'\n',
 "   zgrid            = 'Sigma'\n",
 '   mp               = '+str(levels)+'\n',
 '   top              = 1.0\n',
 '   hstd             = 8000.0d0\n',
 '   given_stability  = .true.\n',
 '   given_vsf        = .false.\n',
 '   ocheck           = .true.\n',
 '/\n',
 '\n',
 '"equiheight_fname" is a filename for the equivalent height.\n',
 '"num_vmode"        is a number of vertical modes.\n'])
    

def write_cnf_hough(n, num_vmode, start_zw, num_zw, maxl, temp, temp_t):

    with open(temp_t+'houghcalc.cnf_ERA5', 'w') as f:
        f.writelines(['&houghcalc_cnf\n',
 '  szw        =  '+str(start_zw)+'\n',
 '  ezw        =  '+str(num_zw)+'\n',
 '  maxl       =  '+str(maxl)+'\n',
 '  my         =  '+str(n)+'\n',
 "  freq_fname = '"+temp+"hough/freq_ERA5.data'\n",
 "  ks_mode    = 'K'\n",
 '  ocheck     = .false.\n',
 '/\n',
 '\n',
 '"ls"         is a zonal wavenumber\n',
 '"num_zw"     is a maximum number of zonal wavenumber, which includes zonal wavenumber 0\n',
 '"maxl"       is a number of each hough mode (EIG, WIG, Rotational modes)\n',
 '"mk"         is a number of grids for meridional direction from EQ to NP\n',
 '"freq_fname" is a filename for the eigenfrequency of shalow water equation\n',
 '"ks_mode"    is a selection for obtaining the eigenvector of rotational mode in\n',
 "             zonal wavenumber 0. 'K' or 'S' should be chosen. The default value is 'K'.\n",
 '"ocheck"     is a logical variable. .true. or .false. should be chosen.\n',
 '             if .true. is chosen, the information about the orthogonality will be displayed.\n',
 '\n',
 '&meridional_grid\n',
 "   ygrid_fname = '"+temp+"gauss/gauss_ERA5.data'\n",
 '/\n',
 '\n',
 '&vsf_cnf\n',
 "  equiheight_fname = '"+temp+"vsf/equi_ERA5.data'\n",
 '  num_vmode        = '+str(num_vmode)+'\n',
 '/\n',
 '"equiheight_fname" is a filename for the equivalent height.\n',
 '"num_vmode" is a number of vertical modes.\n',
 '\n',
 '&output\n',
 '  output_gmt  = .false.\n',
 "  ofname_gmt  = '"+temp+"hough/hough_gmt_ERA5'\n",
 "  ofname_bin  = '"+temp+"hough/h_IC'\n",
 "  bin_combine = 'zonal'\n",
 '/\n',
 '"output_gmt" is a logical variable. If .true. is chosen, the \n',
 '"bin_combine" \n'])
   

def write_cnf_exp(m, n, levels, times, timestep, sigma_file, levels_file, num_vmode, num_zw, maxl, origin, temp):

    start_time = times[0]
    end_time = times[-1]

    with open(temp+'/normal.cnf_ERA5', 'w') as f:
        f.writelines(['&normal_cnf\n',
 '   nx              = '+str(m)+'\n',
 '   ny              = '+str(n)+'\n',
 '   nz              = '+str(levels)+'\n',
 '   nstep           =  1\n',
 "   coef3DNMF_fname = '"+temp+"coef/Hough_ERA5_'\n",
 '   output_3DNMF    = .true.\n',
 '   saveps          = .false.\n',
 '   savemeant       = .false.\n',
 "   ps_fname        = '"+temp+"coef/Ps_ERA5_'\n",
 "   meant_fname     = '"+temp+"coef/Tmean_ERA5_'\n",
 '   saveasci        = .false.\n',
 "   afname          = '"+temp+"coef/InputData_ERA5_'\n",
 "   aformat         = '(96E20.4,1x)'\n",
 '   savehoughwind   = .false.\n',
 '   savenc          = .true.\n',
 "   ncname          = '"+temp+"coef/Hough_coeff_ERA5_'\n",
 '/\n',
 '\n',
 '&time\n',
 "   datetype = 'yyyymmddhh'\n",
 '   syear    = '+str(start_time.year)+'\n',
 '   smon     = '+str(start_time.month)+'\n',
 '   sday     = '+str(start_time.day)+'\n',
 '   shour    = '+str(start_time.hour)+'\n',
 '   smins    = '+str(start_time.minute)+'\n',
 '   ssec     = '+str(start_time.second)+'\n',
 '   slen     = 00\n',
 '   eyear    = '+str(end_time.year)+'\n',
 '   emon     = '+str(end_time.month)+'\n',
 '   eday     = '+str(end_time.day)+'\n',
 '   ehour    = '+str(end_time.hour)+'\n',
 '   emins    = '+str(end_time.minute)+'\n',
 '   esec     = '+str(end_time.second)+'\n',
 '   elen     = 00\n',
 '   dt       = '+str(timestep)+'\n',
 '/\n',
 '\n',
 '&input_data\n',
 "   dataformat_input = 'netcdf'\n",
 "   orig             = 'ECMWF'\n",
 "   zgrid_type       = 'hybrid'\n",
 "   ifile_orog       = ''\n",
 '   numoffile        = 1\n',
 "   ifile_head(1)    =  '"+origin+"UVTQSZ_'\n",
 "   ifile_head(2)    =  ''\n",
 '/\n',
 '\n',
 '&hough_cnf\n',
 "   hough_fname = '"+temp+"hough/h_IC'\n",
 '   num_zw      = '+str(num_zw)+'\n',
 '   maxl        = '+str(maxl)+'\n',
 '   my          = '+str(n)+'\n',
 '/\n',
 '\n',
 '"num_zw" is a maximum number of zonal wavenumber, which includes zonal wavenumber 0\n',
 '"maxl" is a number of all hough modes (EIG, WIG, Rotational modes)\n',
 '\n',
 '\n',
 '&meridional_grid\n',
 "   ygrid_fname = '"+temp+"gauss/gauss_ERA5.data'\n",
 '/\n',
 '"grid_fname" is a filename for the meridional grid\n',
 '\n',
 '\n',
 '&vsf_cnf\n',
 "   vsf_fname          = '"+temp+"vsf/vsf_ERA5.data'\n",
 "   vgrid_fname        = '"+sigma_file+"'\n",
 "   equiheight_fname   = '"+temp+"vsf/equi_ERA5.data'\n",
 "   model_level_fname  = '"+levels_file+"'\n",
 '   num_vmode          = '+str(num_vmode)+'\n',
 "   zgrid              = 'Sigma'\n",
 '   mp                 = '+str(levels)+'\n',
 '   top                = 1.0\n',
 '   given_vsf          = .true.\n',
 '/\n',
 '\n',
 '"equiheight_fname" is a filename for the equivalent height.\n',
 '"num_vmode"        is a number of vertical modes.\n'])
        

def write_cnf_inv(m, n, levels, times, timestep, sigma_file, levels_file, num_vmode, num_zw, maxl, eig_n_s, eig_n_e, wig_n_s, wig_n_e, rot_n_s, rot_n_e, kmode_s, kmode_e, vmode_s, vmode_e, temp, result):

    start_time = times[0]
    end_time = times[-1]

    with open(temp+'/normal_inverse.cnf_ERA5', 'w') as f:
        f.writelines(['&normal_cnf_inverse\n',
 '   nx              = '+str(m)+'\n',
 '   ny              = '+str(n)+'\n',
 '   nz              = '+str(levels)+'\n',
 '   nstep           =   1\n',
 "   coef3DNMF_fname = '"+temp+"coef/Hough_ERA5_'\n",
 "   inverse_fname   = '"+temp+"inverse/ERA5_'\n",
 '   inv2hybrid      = .false.\n',
 "   ps_fname        = '"+temp+"coef/Ps_ERA5_'\n",
 "   meant_fname     = '"+temp+"coef/Tmean_ERA5_'\n",
 '   saveasci        = .false.\n',
 "   afname          = '"+temp+"inverse/Inv_ERA5_'\n",
 "   aformat         = '(96E16.4,1x)'\n",
 '   savenc          = .true.\n',
 "   ncname          = '"+result+"'\n",
 '/\n',
 '\n',
 '&time\n',
 "   datetype = 'yyyymmddhh'\n",
 '   syear    = '+str(start_time.year)+'\n',
 '   smon     = '+str(start_time.month)+'\n',
 '   sday     = '+str(start_time.day)+'\n',
 '   shour    = '+str(start_time.hour)+'\n',
 '   smins    = '+str(start_time.minute)+'\n',
 '   ssec     = '+str(start_time.second)+'\n',
 '   slen     = 00\n',
 '   eyear    = '+str(end_time.year)+'\n',
 '   emon     = '+str(end_time.month)+'\n',
 '   eday     = '+str(end_time.day)+'\n',
 '   ehour    = '+str(end_time.hour)+'\n',
 '   emins    = '+str(end_time.minute)+'\n',
 '   esec     = '+str(end_time.second)+'\n',
 '   elen     = 00\n',
 '   dt       = '+str(timestep)+'\n',
 '/\n',
 '\n',
 '&hough_cnf\n',
 "   hough_fname = '"+temp+"hough/h_IC'\n",
 '   num_zw      = '+str(num_zw)+'\n',
 '   maxl        = '+str(maxl)+'\n',
 '   my          = '+str(n)+'\n',
 '   shough      = 1\n',
 '   ehough      = '+str(maxl*3)+'\n',
 '/\n',
 '\n',
 '&meridional_grid\n',
 "   ygrid_fname = '"+temp+"gauss/gauss_ERA5.data'\n",
 '/\n',
 '\n',
 '&filter_cnf\n',
 '   eig_n_s = '+str(eig_n_s)+'\n',
 '   eig_n_e = '+str(eig_n_e)+'\n',
 '   wig_n_s = '+str(wig_n_s)+'\n',
 '   wig_n_e = '+str(wig_n_e)+'\n',
 '   rot_n_s = '+str(rot_n_s)+'\n',
 '   rot_n_e = '+str(rot_n_e)+'\n',
 '   kmode_s = '+str(kmode_s)+'\n',
 '   kmode_e = '+str(kmode_e)+'\n',
 '   vmode_s = '+str(vmode_s)+'\n',
 '   vmode_e = '+str(vmode_e)+'\n',
 '/\n',
 '\n',
 '&vsf_cnf\n',
 "   vsf_fname         = '"+temp+"vsf/vsf_ERA5.data'\n",
 "   vgrid_fname       = '"+sigma_file+"'\n",
 "   equiheight_fname  = '"+temp+"vsf/equi_ERA5.data'\n",
 "   model_level_fname = '"+levels_file+"'\n",
 '   num_vmode         = '+str(num_vmode)+'\n',
 "   zgrid             = 'Sigma'\n",
 '   mp                = '+str(levels)+'\n',
 '   top               = 1.0\n',
 '   given_vsf         = .true.\n',
 '/\n'])